Repository EthVM/EthVM, pull requests merged in 2020-12, with the labels that each got.

#922 devop: refactor known apollo exception and sending errors to Sentry
  CHANGELOG.md
  newclient/src/apollo/exceptions/errorExceptions.ts
  newclient/src/main.ts
  newclient/src/modules/address/handlers/AddressOverview/AddressOverview.vue
  newclient/src/modules/blocks/handlers/BlockDetails/BlockDetails.vue
  newclient/src/modules/favorites/handlers/FavHandlerAddressListRow.vue
  newclient/src/modules/txs/handlers/TxDetails/TxDetails.vue
  newclient/src/modules/uncles/handlers/UncleDetails.vue
Labels: Ready For Review, bug, devop

#923 devop: removed console log and unused comments
  CHANGELOG.md
  newclient/src/modules/App.vue
  newclient/src/modules/tokens/handlers/tokensMarketInfo/TokensMarketInfo.vue
  newclient/src/modules/txs/handlers/TxDetails/TxDetails.vue
Labels: Ready For Review, devop

#929 fix: header disappearance
  CHANGELOG.md
  newclient/src/core/components/layout/TheNavigationDrawer.vue
Labels: Ready For Review, bug

#930 devop: adjust blocks height to 100% on adr page
  CHANGELOG.md
  newclient/src/modules/address/components/AddressDetail.vue
Labels: Ready For Review, devop

#926 Fix displaying app-state-diff
  newclient/src/modules/address/components/TableAddressTxsRow.vue
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
Labels: bug, ready

#927 Devop/fav address ui fix
  CHANGELOG.md
  newclient/src/modules/favorite-addresses/components/FavAddrTableHeader.vue
  newclient/src/modules/favorite-addresses/components/FavAddrTableRow.vue
  newclient/src/modules/favorite-addresses/handlers/FavHandlerAddressList.vue
  newclient/src/modules/favorite-tokens/components/FavSearch.vue
  newclient/src/translations/en_US.json
Labels: devop, ready

#928 Devop/powered by mew link
  CHANGELOG.md
  newclient/src/core/components/layout/TheFooter.vue
  newclient/src/modules/tokens/components/TableTokensRow.vue
Labels: Ready For Review, devop

#942 devop: new route name for unique chart
  CHANGELOG.md
  newclient/src/modules/charts/components/ChartLink.vue
  newclient/src/modules/charts/handlers/TimeSeriesChartData.vue
  newclient/src/modules/charts/models/index.ts
  newclient/src/modules/charts/pages/PageChartsList.vue
  newclient/src/modules/charts/pages/PageUniqueChart.vue
  newclient/src/translations/en_US.json
Labels: Ready For Review, devop

#944 Check on valid hash instead and do not search spaces
  CHANGELOG.md
  newclient/src/modules/search/components/Search.vue
  newclient/src/modules/search/handlers/SearchDetails.vue
Labels: bug, ready

#933 Add invalid hash error to exceptions
  CHANGELOG.md
  newclient/src/apollo/exceptions/errorExceptions.ts
Labels: Ready For Review, bug

#941 chore: remove console logs
  CHANGELOG.md
  newclient/src/modules/favorite-tokens/models/FavSort.ts
Labels: ready

#945 fix: Cannot read property 'insertBefore' of null in Address ERC20 Tok…
  CHANGELOG.md
  newclient/src/modules/address/components/TableAddressTokensHeader.vue
  newclient/src/modules/address/components/TableAddressTokensRow.vue
  newclient/src/modules/address/handlers/AddressTokens/AddressTokens.vue
  newclient/src/modules/address/models/TokenSort.ts
Labels: bug, ready

#939 Add loading for contract
  CHANGELOG.md
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
  newclient/src/modules/address/pages/PageDetailsAddress.vue
Labels: bug, ready

#948 Fix 2096719583
  CHANGELOG.md
  newclient/src/modules/address/components/TableAddressRewardsRow.vue
Labels: bug, ready

#949 Do checksum on only valid addresses
  CHANGELOG.md
  newclient/src/core/components/props/index.ts
  newclient/src/core/components/ui/AppDetailsListRow.vue
  newclient/src/core/filters/toChecksum.ts
  newclient/src/modules/address/pages/PageDetailsAddress.vue
  newclient/src/modules/blocks/handlers/BlockDetails/BlockDetails.vue
  newclient/src/modules/tokens/components/TokenDetails/TokenDetailsList.vue
  newclient/src/modules/txs/handlers/TxDetails/TxDetails.vue
  newclient/src/modules/uncles/handlers/UncleDetails.vue
Labels: bug, ready

#947 fix: chart rendering with options update on different units
  CHANGELOG.md
  newclient/src/apollo/schemas/api.json
  newclient/src/modules/address/handlers/AddressOverview/apolloTypes/getContractTimestamp.ts
  newclient/src/modules/charts/components/Chart.vue
  newclient/src/modules/charts/handlers/HomeGasPriceChart.vue
  newclient/src/modules/charts/handlers/HomeTxChart.vue
  newclient/src/modules/charts/handlers/TimeSeriesChartData.vue
  newclient/src/modules/charts/mixins/ChartDataMixin.mixin.ts
  newclient/src/modules/charts/mixins/apolloTypes/getTimestamp.ts
  newclient/src/modules/charts/mixins/getServerTimestamp.graphql
  newclient/src/modules/txs/handlers/TxDetails/apolloTypes/getTransactionByHash.ts
Labels: bug, ready

#936 fix: invariant violation in fetchMore
  CHANGELOG.md
  newclient/src/apollo/exceptions/errorExceptions.ts
  newclient/src/modules/address/handlers/AddressRewards/AddressRewards.vue
  newclient/src/modules/address/handlers/AddressTokens/AddressTokens.vue
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
  newclient/src/modules/blocks/handlers/RecentBlocks/RecentBlocks.vue
  newclient/src/modules/tokens/handlers/tokenHolders/TokenHolders.vue
  newclient/src/modules/tokens/handlers/tokenTransfers/TokenTransfers.vue
  newclient/src/modules/txs/handlers/BlockTxs/BlockTxs.vue
Labels: bug, ready

#940 fix: prevent appolo requests with invalid addressRef in token details
  newclient/src/modules/tokens/pages/PageDetailsToken.vue
Labels: bug, ready

#950 fix: old name is shown in edit/remove dialog, after change
  newclient/src/modules/favorite-addresses/handlers/FavHandlerEdit.vue
Labels: bug, ready
