Repository EthVM/EthVM, pull requests merged in 2020-06, with the labels that each got.

#778 Bug/ts errors
  client/src/modules/uncles/components/TableUncles.vue
  newclient/src/modules/txs/handlers/TxDetails/TxDetails.vue
  newclient/src/modules/uncles/components/TableUncles.vue
Labels: bug

#781 Tokens Table
  newclient/src/core/helper/number-format-helper.ts
  newclient/src/core/router/index.ts
  newclient/src/modules/App.vue
  newclient/src/modules/tokens/components/TableTokensHeader.vue
  newclient/src/modules/tokens/components/TableTokensRow.vue
  newclient/src/modules/tokens/components/TokenTableRowLoading.vue
  newclient/src/modules/tokens/handlers/TokensMarketInfo.vue
  newclient/src/modules/tokens/pages/PageTokes.vue
  newclient/src/plugins/CoinData/index.ts
  newclient/src/plugins/CoinData/models/index.ts
  newclient/yarn.lock
Labels: project: FrontEnd

#784 Feat/token prices address
  newclient/src/modules/address/components/TableAddressTokensRow.vue
  newclient/src/modules/address/components/props/index.ts
  newclient/src/modules/address/handlers/AddressTokens/AddressTokens.vue
  newclient/src/plugins/CoinData/index.ts
Labels: ready

#785 Refactor/tkn page
  newclient/apollo/schemas/api.json
  newclient/src/core/components/ui/AppDetailsListRow.vue
  newclient/src/core/router/index.ts
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
  newclient/src/modules/address/handlers/AddressTransfers/apolloTypes/getAdrErc20Transfers.ts
  newclient/src/modules/address/handlers/AddressTransfers/transfers.graphql
  newclient/src/modules/tokens/components/TokenDetails/TokenDetailsList.vue
  newclient/src/modules/tokens/components/TokenDetailsHolder/TokenTableHolders.vue
  newclient/src/modules/tokens/components/TokenDetailsHolder/TokenTableHoldersRow.vue
  newclient/src/modules/tokens/components/TokenDetailsHolder/TokenTableHoldersRowLoading.vue
  newclient/src/modules/tokens/components/Transfers/TransfersTable.vue
  newclient/src/modules/tokens/components/Transfers/TransfersTableRow.vue
  newclient/src/modules/tokens/components/Transfers/TransfersTableRowLoading.vue
  newclient/src/modules/tokens/handlers/tokenDetails/TokenDetails.vue
  newclient/src/modules/tokens/handlers/tokenDetails/apolloTypes/ERC20TokenOwnerDetails.ts
  newclient/src/modules/tokens/handlers/tokenDetails/apolloTypes/ERC20TokenOwners.ts
  newclient/src/modules/tokens/handlers/tokenDetails/apolloTypes/TokenDetails.ts
  newclient/src/modules/tokens/handlers/tokenDetails/apolloTypes/getERC20TokenBalance.ts
  newclient/src/modules/tokens/handlers/tokenDetails/apolloTypes/getERC20TokenOwners.ts
  newclient/src/modules/tokens/handlers/tokenDetails/apolloTypes/getTokenInfoByContract.ts
  newclient/src/modules/tokens/handlers/tokenDetails/tokenDetails.graphql
  newclient/src/modules/tokens/handlers/transfers/apolloTypes/TokenFragment.ts
  newclient/src/modules/tokens/handlers/transfers/apolloTypes/TransferSummary.ts
  newclient/src/modules/tokens/handlers/transfers/apolloTypes/getERC20Transfer.ts
  newclient/src/modules/tokens/handlers/transfers/apolloTypes/getERC20Transfers.ts
  newclient/src/modules/tokens/handlers/transfers/transfers.graphql
  newclient/src/modules/tokens/pages/PageDetailsToken.vue
  newclient/src/modules/txs/components/TableTxs.vue
  tsconfig.json
Labels: project: FrontEnd, ready
