Repository EthVM/EthVM, pull requests merged in 2020-07, with the labels that each got.

#774 Devop/commitlint
  newclient/commitlint.config.js
  newclient/package.json
Labels: enhancement, ready

#786 Feat/addr tokens nft
  newclient/src/modules/address/components/TableAddressTokensHeader.vue
  newclient/src/modules/address/components/TableAddressTokensRow.vue
  newclient/src/modules/address/components/TableAddressUniqueNft.vue
  newclient/src/modules/address/handlers/AddressTokens/AddressTokens.vue
  newclient/src/modules/address/pages/PageDetailsAddress.vue
  newclient/src/translations/en_US.json
Labels: ready

#787 Refactor/pending tx
  newclient/src/modules/address/components/TableAddressTxsRow.vue
  newclient/src/modules/address/handlers/AddressPendingTx/AddressPendingTx.vue
  newclient/src/modules/address/handlers/AddressPendingTx/apolloTypes/getPendingTransactions.ts
  newclient/src/modules/address/handlers/AddressPendingTx/pendingTxs.graphql
  newclient/src/modules/address/pages/PageDetailsAddress.vue
Labels: ready

#788 Add check after update & add check for tx
  newclient/src/core/components/ui/AppDetailsList.vue
  newclient/src/modules/blocks/handlers/RecentBlocks/RecentBlocks.vue
  newclient/src/modules/txs/components/TableTxsRow.vue
  newclient/src/modules/txs/handlers/TxDetails/TxDetails.vue
Labels: bug, ready

#789 feat: address subscription events
  newclient/src/apollo/global/globalTypes.ts
  newclient/src/core/components/ui/AppNewUpdate.vue
  newclient/src/modules/address/components/AddressDetail.vue
  newclient/src/modules/address/handlers/AddressOverview/AddressOverview.vue
  newclient/src/modules/address/handlers/AddressRewards/AddressRewards.vue
  newclient/src/modules/address/handlers/AddressTokens/AddressTokens.vue
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
  newclient/src/modules/address/handlers/AddressUpdateEvent/AddressUpdateEvent.mixin.ts
  newclient/src/modules/address/handlers/AddressUpdateEvent/addressEvent.graphql
  newclient/src/modules/address/handlers/AddressUpdateEvent/apolloTypes/addressEvent.ts
  newclient/src/modules/address/pages/PageDetailsAddress.vue
  newclient/src/translations/en_US.json
Labels: ready

#791 Fix: BUG - Add value to tx
  newclient/src/modules/address/components/TableAddressTxsRow.vue
Labels: bug, ready

#794 Fix/block updates
  newclient/src/core/components/ui/AppInfoCard.vue
  newclient/src/main.ts
  newclient/src/modules/address/components/AddressDetail.vue
  newclient/src/modules/blocks/handlers/BlockStats/BlockStats.vue
Labels: ready

#793 Move search, fix timestamps and remove space on search
  newclient/src/apollo/schemas/api.json
  newclient/src/core/components/layout/TheNavigationDrawer.vue
  newclient/src/core/components/ui/AppSearch.vue
  newclient/src/modules/blocks/handlers/BlockDetails/BlockDetails.vue
  newclient/src/modules/search/components/Search.vue
  newclient/src/modules/search/handlers/SearchDetails.vue
  newclient/src/modules/search/handlers/apolloTypes/TokenSearch.ts
  newclient/src/modules/search/handlers/apolloTypes/getHashType.ts
  newclient/src/modules/search/handlers/apolloTypes/getTokensBeginsWith.ts
  newclient/src/modules/search/handlers/searchDetails.graphql
  newclient/src/modules/tokens/components/Transfers/TransfersTableRow.vue
  newclient/src/modules/txs/handlers/TxDetails/TxDetails.vue
  newclient/src/modules/uncles/handlers/UncleDetails.vue
  newclient/src/modules/uncles/pages/PageDetailsUncle.vue
Labels: bug, ready
