Repository EthVM/EthVM, pull requests merged in 2020-11, with the labels that each got.

#910 merge master to develop
  CHANGELOG.md
  newclient/package.json
  newclient/vue.config.js
Labels: Ready For Review

#914 Address contract details
  CHANGELOG.md
  newclient/src/apollo/schemas/api.json
  newclient/src/modules/address/components/props/index.ts
  newclient/src/modules/address/handlers/AddressOverview/AddressOverview.vue
  newclient/src/modules/address/handlers/AddressOverview/addressDetails.graphql
  newclient/src/modules/address/handlers/AddressOverview/apolloTypes/getTransaction.ts
  newclient/src/modules/address/models/ErrorMessagesForAddress.ts
  newclient/src/modules/address/pages/PageDetailsAddress.vue
  newclient/src/translations/en_US.json
Labels: Ready For Review, feature

#909 Address detail token sort
  CHANGELOG.md
  newclient/src/core/components/ui/AppFilter.vue
  newclient/src/core/components/ui/AppTableTitle.vue
  newclient/src/modules/address/components/TableAddressTokensHeader.vue
  newclient/src/modules/address/components/TableAddressTokensRow.vue
  newclient/src/modules/address/handlers/AddressTokens/AddressTokens.vue
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
  newclient/src/modules/address/models/TokenSort.ts
  newclient/src/modules/favorites/components/FavAddrTableHeader.vue
  newclient/src/modules/favorites/handlers/FavHandlerAddressList.vue
  newclient/src/modules/favorites/models/FavSort.ts
  newclient/src/modules/tokens/components/TableTokensHeader.vue
  newclient/src/modules/tokens/handlers/tokensMarketInfo/TokensMarketInfo.vue
Labels: feature, ready

#912 feat: display contract address when transaction created a contract
  CHANGELOG.md
  newclient/src/core/components/props/index.ts
  newclient/src/modules/address/components/props/index.ts
  newclient/src/modules/txs/handlers/TxDetails/TxDetails.vue
  newclient/src/modules/txs/handlers/TxDetails/apolloTypes/TxDetails.ts
  newclient/src/modules/txs/handlers/TxDetails/txDetails.graphql
Labels: Ready For Review, feature

#903 fix: removed to render on contract creation
  CHANGELOG.md
  newclient/src/modules/address/components/TableAddressTxsRow.vue
  newclient/src/modules/txs/components/TableTxsRow.vue
Labels: Ready For Review, bug

#911 Devop/enforce branch names
  CHANGELOG.md
  newclient/checkBranch.sh
  newclient/package.json
Labels: Ready For Review, devop

#913 Hide state diff if failed tx
  CHANGELOG.md
  newclient/src/modules/address/components/TableAddressTxsRow.vue
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
  newclient/src/modules/address/handlers/AddressTransfers/apolloTypes/getTransactionStateDiff.ts
  newclient/src/modules/address/handlers/AddressTransfers/transfers.graphql
  newclient/src/modules/address/models/TokenSort.ts
  newclient/src/modules/address/pages/PageDetailsAddress.vue
  newclient/src/modules/favorites/models/FavSort.ts
Labels: Ready For Review, bug

#918 Fix/long nft token id display
  CHANGELOG.md
  newclient/src/modules/address/components/TableAddressTransfersRow.vue
  newclient/src/modules/tokens/components/TokenDetailsTransfer/TokenTableTransfersRow.vue
Labels: Ready For Review, bug
