Repository EthVM/EthVM, pull requests merged in 2020-10, with the labels that each got.

#868 Add a test action
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-ethvmbuilds.yml
  .github/workflows/create-release.yml
  newclient/package.json
  newclient/src/configs.ts
  newclient/src/core/router/index.ts
  newclient/src/main.ts
  newclient/src/modules/App.vue
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
  newclient/vue.config.js
Labels: ready

#866 fix readme grammar
  README.md
Labels: ready

#871 Add sentry environment
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-ethvmbuilds.yml
  .github/workflows/create-release.yml
  CHANGELOG.md
  newclient/package.json
  newclient/src/main.ts
  newclient/src/modules/txs/components/props/index.ts
Labels: ready

#869 Chart font bug
  CHANGELOG.md
  newclient/src/modules/charts/components/Chart.vue
Labels: bug, ready

#870 Convert all instances of address to checksum before getting concatenated
  CHANGELOG.md
  newclient/package.json
  newclient/src/core/components/ui/AppDetailsListRow.vue
  newclient/src/core/components/ui/AppTransformHash.vue
  newclient/src/core/filters/toChecksum.ts
  newclient/src/main.ts
  newclient/src/modules/address/components/AddressDetail.vue
  newclient/src/modules/address/components/TableAddressTokensRow.vue
  newclient/src/modules/address/components/TableAddressTransfersRow.vue
  newclient/src/modules/address/components/TableAddressTxsRow.vue
  newclient/src/modules/blocks/components/BlockDetailsTitle.vue
  newclient/src/modules/blocks/components/TableBlocksRow.vue
  newclient/src/modules/tokens/components/TokenDetailsHolder/TokenTableHoldersRow.vue
  newclient/src/modules/tokens/components/TokenDetailsTransfer/TokenTableTransfersRow.vue
  newclient/src/modules/txs/components/TableTxsRow.vue
Labels: ready

#873 Fix types
  CHANGELOG.md
  newclient/src/modules/address/components/TableAddressTransfersRow.vue
Labels: ready

#874 Devop/fix base path config
  newclient/package.json
  newclient/src/core/components/layout/TheNavigationDrawer.vue
  newclient/src/core/components/mixins/CoinData/CoinData.mixin.ts
  newclient/src/core/components/ui/AppBreadCrumbs.vue
  newclient/src/core/components/ui/AppCopyToClip.vue
  newclient/src/core/components/ui/AppFilter.vue
  newclient/src/core/components/ui/AppFootnotes.vue
  newclient/src/core/components/ui/AppGreeting.vue
  newclient/src/core/components/ui/AppLanguage.vue
  newclient/src/core/components/ui/AppMessage.vue
  newclient/src/core/components/ui/AppNewUpdate.vue
  newclient/src/core/components/ui/AppStateDiff.vue
  newclient/src/core/components/ui/AppTabs.vue
  newclient/src/main.ts
  newclient/src/modules/address/components/Blockies.vue
  newclient/src/modules/address/components/TableAddressRewardsRow.vue
  newclient/src/modules/address/components/TableAddressTokensRow.vue
  newclient/src/modules/address/components/TableAddressTransfersRow.vue
  newclient/src/modules/address/components/TableAddressUniqueNft.vue
  newclient/src/modules/address/components/UniqueNftRow.vue
  newclient/src/modules/address/handlers/AddressOverview/AddressOverview.vue
  newclient/src/modules/address/handlers/AddressPendingTx/AddressPendingTx.vue
  newclient/src/modules/address/handlers/AddressRewards/AddressRewards.vue
  newclient/src/modules/address/handlers/AddressRewards/BlockUncleRewards.vue
  newclient/src/modules/address/handlers/AddressTokens/AddressTokens.vue
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
  newclient/src/modules/address/handlers/AddressUpdateEvent/AddressUpdateEvent.mixin.ts
  newclient/src/modules/txs/components/TableTxsRow.vue
  newclient/vue.config.js
Labels: ready

#872 Devop/replace hardcoded version
  CHANGELOG.md
  newclient/src/core/components/layout/TheFooter.vue
  newclient/src/modules/address/components/TableAddressTransfersRow.vue
Labels: ready

#875 Fix missing translations in tokens details page
  CHANGELOG.md
  newclient/src/modules/tokens/components/TokenDetails/TokenDetailsList.vue
  newclient/src/modules/tokens/components/TokenDetailsHolder/TokenTableHoldersRow.vue
  newclient/src/modules/tokens/handlers/tokenDetails/TokenDetails.vue
  newclient/src/translations/en_US.json
Labels: ready

#879 Devop/public path bug
  CHANGELOG.md
  newclient/package.json
  newclient/public/index.html
  newclient/vue.config.js
Labels: Ready For Review

#880 replaced router-link-tag with a-tag
  newclient/src/core/components/layout/TheFooter.vue
Labels: Ready For Review

#888 devop/add-release-script
  .github/workflows/create-release.yml
  release.sh
Labels: ready

#896 Update mewbot api
  .github/workflows/create-release.yml
Labels: Ready For Review

#885 bug/live-charts
  CHANGELOG.md
  newclient/src/modules/charts/handlers/HomeGasPriceChart.vue
  newclient/src/modules/charts/handlers/HomeTxChart.vue
Labels: ready

#898 Comment out signing for now
  release.sh
Labels: ready

#884 Devop/comment on methods
  newclient/package.json
  newclient/src/modules/address/handlers/AddressUpdateEvent/AddressUpdateEvent.mixin.ts
  newclient/src/modules/address/pages/PageDetailsAddress.vue
  newclient/src/modules/blocks/components/BlockDetailsTitle.vue
  newclient/src/modules/blocks/components/NoticeNewBlock.vue
  newclient/src/modules/blocks/components/TableBlocksRow.vue
  newclient/src/modules/blocks/handlers/BlockDetails/BlockDetails.vue
  newclient/src/modules/blocks/handlers/BlockStats/BlockStats.vue
  newclient/src/modules/blocks/handlers/RecentBlocks/RecentBlocks.vue
  newclient/src/modules/blocks/pages/PageBlocks.vue
  newclient/src/modules/blocks/pages/PageDetailsBlock.vue
  newclient/src/modules/charts/components/Chart.vue
  newclient/src/modules/charts/components/ChartLink.vue
  newclient/src/modules/charts/handlers/TimeSeriesChartData.vue
  newclient/src/modules/charts/mixins/ChartDataMixin.mixin.ts
  newclient/src/modules/home/pages/PageHome.vue
  newclient/src/modules/search/components/Search.vue
  newclient/src/modules/search/handlers/SearchDetails.vue
  newclient/src/modules/tokens/components/TableTokensHeader.vue
  newclient/src/modules/tokens/components/TokenDetails/TokenDetailsList.vue
  newclient/src/modules/tokens/components/TokenDetailsHolder/TokenTableHolders.vue
  newclient/src/modules/tokens/components/TokenDetailsHolder/TokenTableHoldersRow.vue
  newclient/src/modules/tokens/components/TokenDetailsTransfer/TokenTableTransfers.vue
  newclient/src/modules/tokens/components/TokenDetailsTransfer/TokenTableTransfersRow.vue
  newclient/src/modules/tokens/handlers/tokenDetails/TokenDetails.vue
  newclient/src/modules/tokens/handlers/tokenHolders/TokenHolders.vue
  newclient/src/modules/tokens/handlers/tokenTransfers/TokenTransfers.vue
  newclient/src/modules/tokens/handlers/tokensMarketInfo/TokensMarketInfo.vue
  newclient/src/modules/tokens/pages/PageDetailsToken.vue
  newclient/src/modules/tokens/pages/PageTokes.vue
  newclient/src/modules/txs/handlers/BlockTxs/BlockTxs.vue
  newclient/src/modules/txs/handlers/PendingTxs/PendingTxs.vue
  newclient/src/modules/txs/handlers/TxDetails/TxDetails.vue
  newclient/src/modules/txs/pages/PageDetailsTx.vue
  newclient/src/modules/txs/pages/PagePendingTxs.vue
  newclient/src/modules/txs/pages/PageTxs.vue
  newclient/src/modules/uncles/handlers/UncleDetails.vue
  newclient/src/modules/uncles/pages/PageDetailsUncle.vue
  newclient/vue.config.js
  newclient/yarn.lock
Labels: ready

#883 devop/use-address-vars
  CHANGELOG.md
  newclient/src/core/components/layout/TheFooter.vue
Labels: ready

#881 Catch v-img @errors
  CHANGELOG.md
  newclient/src/modules/address/components/TableAddressTokensRow.vue
  newclient/src/modules/address/components/TableAddressTransfersRow.vue
  newclient/src/modules/address/handlers/AddressUpdateEvent/AddressUpdateEvent.mixin.ts
  newclient/src/modules/charts/mixins/ChartDataMixin.mixin.ts
  newclient/src/modules/tokens/components/TableTokensRow.vue
  newclient/src/modules/tokens/components/TokenDetails/TokenDetailsList.vue
Labels: ready

#887 Change to price change percentage
  CHANGELOG.md
  newclient/apollo/schemas/api.json
  newclient/src/apollo/schemas/api.json
  newclient/src/core/components/mixins/CoinData/apolloTypes/getLatestPrices.ts
  newclient/src/core/components/mixins/CoinData/getLatestPrices.graphql
  newclient/src/modules/address/components/TableAddressTokensRow.vue
  newclient/src/modules/tokens/components/TableTokensRow.vue
  newclient/src/modules/tokens/components/TokenDetails/TokenDetailsList.vue
Labels: ready

#895 Add lowercase and data check
  CHANGELOG.md
  newclient/src/core/components/mixins/CoinData/CoinData.mixin.ts
  newclient/src/modules/address/handlers/AddressPendingTx/AddressPendingTx.vue
  newclient/src/modules/search/handlers/SearchDetails.vue
Labels: bug, ready

#891 Fix incorrect padding
  CHANGELOG.md
  newclient/src/modules/address/components/AddressDetail.vue
Labels: ready

#899 fix: fixed hash transform to be easily copied
  CHANGELOG.md
  newclient/src/core/components/ui/AppTransformHash.vue
Labels: ready

#890 Update token arrow sort
  CHANGELOG.md
  newclient/src/modules/tokens/components/TableTokensHeader.vue
Labels: ready

#905 pending tx status refactor and mined blinker fix
  CHANGELOG.md
  newclient/package.json
  newclient/src/modules/address/components/TableAddressTxsRow.vue
  newclient/src/modules/address/handlers/AddressPendingTx/AddressPendingTx.vue
  newclient/src/modules/txs/components/TableTxsRow.vue
  newclient/src/modules/txs/handlers/PendingTxs/PendingTxs.vue
Labels: Ready For Review, project: FrontEnd

#882 Devop/depcheck commitlint
  CHANGELOG.md
  newclient/.depcheckrc
  newclient/.eslintrc.js
  newclient/commitlint.config.js
  newclient/package.json
  newclient/src/modules/address/components/TableAddressTokensRow.vue
  newclient/src/modules/favorites/components/FavDialog.vue
  newclient/vue.config.js
  newclient/yarn.lock
Labels: ready
