Repository EthVM/EthVM, pull requests merged in 2022-01, with the labels that each got.

#973 Bug/fav tokens
  newclient/src/apollo/favorite-tokens/resolvers.ts
  newclient/src/modules/favorite-addresses/handlers/FavHandlerEdit.vue
  newclient/src/modules/favorite-addresses/mixins/FavActions.mixin.ts
Labels: bug, Ready For Review

#976 devop: update package version, add snackbar message on copy
  newclient/package.json
  newclient/src/core/components/ui/AppCopyToClip.vue
  newclient/src/translations/en_US.json
  newclient/yarn.lock
Labels: ready, devop

#974 Bug/uncles
  newclient/src/apollo/schemas/api.json
  newclient/src/core/router/index.ts
  newclient/src/modules/uncles/components/TableUnclesRow.vue
  newclient/src/modules/uncles/components/TableUnclesRowLoading.vue
  newclient/src/modules/uncles/handlers/UncleDetails.vue
  newclient/src/modules/uncles/handlers/apolloTypes/UncleDetails.ts
  newclient/src/modules/uncles/handlers/apolloTypes/getUncleByHash.ts
  newclient/src/modules/uncles/handlers/uncleDetails.graphql
  newclient/src/modules/uncles/pages/PageDetailsUncle.vue
  newclient/src/modules/uncles/pages/PageUncles.vue
Labels: bug, ready

#979 devop: retry on fetch fail apollo provider
  newclient/package.json
  newclient/src/apollo/apolloProvider.ts
  newclient/src/main.ts
  newclient/yarn.lock
Labels: ready

#986 devop: add check for 0 fee transfers
  newclient/src/apollo/apolloProvider.ts
  newclient/src/core/components/ui/AppTabs.vue
  newclient/src/modules/address/components/TableAddressTxsRow.vue
  newclient/src/modules/search/handlers/SearchDetails.vue
Labels: bug, Ready For Review

#989 Feat/token filter
  newclient/src/modules/address/handlers/AddressTokens/AddressTokens.vue
Labels: ui
