Repository EthVM/EthVM, pull requests merged in 2022-11, with the labels that each got.

#1064 Feat/portfolio totals
  v2/src/core/components/AppAddressBlockie.vue
  v2/src/core/components/AppBtn.vue
  v2/src/core/components/AppTokenIcon.vue
  v2/src/core/composables/AddressTokens/addressTokens.composable.ts
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/ModulePortfolioBalances.vue
  v2/src/modules/address/ModulePortfolioList.vue
  v2/src/modules/address/ModulePortfolioTokenBalance.vue
  v2/src/modules/address/ModulePortfolioTotal.vue
  v2/src/modules/address/components/AddressBalanceTotals.vue
  v2/src/store/index.ts
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewAddressOverview.vue
  v2/src/views/ViewPortfolio.vue
Labels: feature, v2

#1067 Feat/portfolio filter balances
  v2/src/App.vue
  v2/src/core/components/AppInput.vue
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/ModulePortfolioTokenBalance.vue
  v2/src/modules/address/components/TableRowPortfolioItem.vue
  v2/src/store/index.ts
  v2/src/views/ViewPortfolio.vue
Labels: feature, ui, v2

#1069 Feat/portfolio header UI
  v2/src/core/components/AppBtn.vue
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/ModulePortfolioBalances.vue
  v2/src/modules/address/ModulePortfolioTotal.vue
  v2/src/modules/chart/components/ChartPie.vue
  v2/src/store/index.ts
  v2/src/views/ViewPortfolio.vue
Labels: ui, v2

#1066 feat: 🎸 add all eth transfers tabs
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/core/components/AppChip.vue
  v2/src/modules/address/ModuleAddressTransferHistory.vue
  v2/src/modules/address/ModuleAllAndInternalEthTransfers.vue
  v2/src/modules/address/ModulePendingEthTransfers.vue
  v2/src/modules/address/apollo/EthTransfers/allTransfers.generated.ts
  v2/src/modules/address/apollo/EthTransfers/allTransfers.graphql
  v2/src/modules/address/components/EthBalanceTabs/TableAllAndInternalRow.vue
  v2/src/modules/address/components/EthBalanceTabs/TableMinedAndPendingRow.vue
  v2/src/styles/main.scss
  v2/src/views/ViewAddressEthBalance.vue
Labels: ui, v2, refactor

#1072 Fix/minor UI fixes
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/components/TableRowNftTransfers.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTableRow.vue
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/components/TxsTableRow.vue
Labels: bug, v2

#1070 feat: label adr
  v2/src/core/components/AppInput.vue
  v2/src/core/components/AppTransformHash.vue
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/components/TableRowPortfolioItem.vue
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTableRow.vue
  v2/src/modules/tokens/components/TokenDetailsSocials.vue
  v2/src/modules/tokens/components/TokenMarketInfo/TableRowTokenMarketInfo.vue
  v2/src/store/index.ts
  v2/src/views/ViewAddress.vue
Labels: feature, v2
