Repository EthVM/EthVM, pull requests merged in 2022-09, with the labels that each got.

#1034 Feat/refactor nft transfers
  v2/pnpm-lock.yaml
  v2/src/core/components/AppChip.vue
  v2/src/core/components/AppTransformHash.vue
  v2/src/core/composables/AddressUpdate/addressUpdate.composable.ts
  v2/src/core/router/index.ts
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressNfts.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/apollo/AddressTransfers/transfers.generated.ts
  v2/src/modules/address/apollo/AddressTransfers/transfers.graphql
  v2/src/styles/main.scss
  v2/src/views/ViewAddressNfts.vue
  v2/src/views/ViewAddressOverview.vue
Labels: v2

#1036 Test Api
  .github/workflows/add-to-builds-api-test.yml
  .github/workflows/add-to-ethvmbuilds.yml
  newclient/apollo.config.js
  newclient/package.json
  newclient/src/apollo/global/globalTypes.ts
  newclient/src/apollo/schemas/api.json
  newclient/src/configs.ts
  newclient/src/core/components/layout/TheNavigationDrawer.vue
  newclient/src/core/router/index.ts
  newclient/src/modules/address/handlers/AddressOverview/apolloTypes/getEthBalance.ts
  newclient/src/modules/address/handlers/AddressRewards/apolloTypes/getAddrRewardsBlock.ts
  newclient/src/modules/address/handlers/AddressTransfers/AddressTransfers.vue
  newclient/src/modules/address/handlers/AddressTransfers/apolloTypes/getAddressERC721Transfers.ts
  newclient/src/modules/address/handlers/AddressTransfers/apolloTypes/getAddressEthTransfers.ts
  newclient/src/modules/address/handlers/AddressTransfers/transfers.graphql
  newclient/src/modules/address/handlers/AdressContractInfo/apolloTypes/getContractInfo.ts
  newclient/src/modules/home/pages/PageHome.vue
  newclient/src/modules/search/handlers/apolloTypes/getHashType.ts
  newclient/src/modules/tokens/handlers/tokenTransfers/apolloTypes/getERC721TokenTransfers.ts
  newclient/src/modules/tokens/handlers/tokenTransfers/tokenTransfers.graphql
Labels: devop

#1042 fix: add correct var name
  CHANGELOG.md
  newclient/src/modules/address/components/TableAddressTransfersRow.vue
  newclient/src/modules/tokens/components/TokenDetailsTransfer/TokenTableTransfersRow.vue
Labels: bug

#1037 Feat/token market info UI
  v2/src/App.vue
  v2/src/core/components/TheAppHeader.vue
  v2/src/core/router/index.ts
  v2/src/modules/tokens/ModuleTokensInfo.vue
  v2/src/modules/tokens/components/TokenMarketInfo/TableRowTokenMarketInfo.vue
  v2/src/views/ViewTokens.vue
Labels: ui, v2

#1046 Feat/refactor recent blocks and txs
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/modules/block/ModuleBlockStats.vue
  v2/src/modules/block/ModuleRecentBlocks.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTable.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTableRow.vue
  v2/src/modules/block/components/RecentBlocks/NoticeNewBlock.vue
  v2/src/modules/tokens/ModuleTokenDetails.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/apollo/transfersQuery.generated.ts
  v2/src/modules/txs/apollo/transfersQuery.graphql
  v2/src/modules/txs/components/TxsTable.vue
  v2/src/modules/txs/components/TxsTableRow.vue
  v2/src/views/ViewBlocksAndTransactions.vue
Labels: ui, v2, refactor

#1052 Bring v2/develop client up to date
  CHANGELOG.md
  newclient/package.json
  newclient/src/modules/address/components/TableAddressTransfersRow.vue
  newclient/src/modules/address/handlers/AdressContractInfo/AddressContractInfo.vue
  newclient/src/modules/tokens/components/TokenDetailsTransfer/TokenTableTransfersRow.vue
Labels: chore
