Repository EthVM/EthVM, pull requests merged in 2022-10, with the labels that each got.

#1054 Fix/UI alpha prep
  v2/src/App.vue
  v2/src/assets/block-stats-icons/block.svg
  v2/src/assets/block-stats-icons/eth.svg
  v2/src/assets/block-stats-icons/gas.svg
  v2/src/assets/block-stats-icons/time.svg
  v2/src/assets/logo-compact.png
  v2/src/assets/logo.svg
  v2/src/core/components/AppSearch.vue
  v2/src/core/components/AppTabs.vue
  v2/src/core/components/TheAppHeader.vue
  v2/src/core/components/TheAppNavigationDrawer.vue
  v2/src/core/components/props/index.ts
  v2/src/core/plugins/vuetify.ts
  v2/src/modules/address/components/TableRowAddressTokenTransfers.vue
  v2/src/modules/address/components/TableRowNftTransfers.vue
  v2/src/modules/block/ModuleBlockStats.vue
  v2/src/modules/block/components/BlockStatsCard.vue
  v2/src/modules/tokens/ModuleTokenDetails.vue
  v2/src/styles/settings.scss
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewAddressMiners.vue
  v2/src/views/ViewAddressNfts.vue
  v2/src/views/ViewAddressTokens.vue
  v2/src/views/ViewBlocksAndTransactions.vue
  v2/src/views/ViewHome.vue
Labels: ui, v2

#1049 Feat/block details page UI
  v2/pnpm-lock.yaml
  v2/src/core/components/AppBtnIcon.vue
  v2/src/core/components/AppTransformHash.vue
  v2/src/core/helper/timeago.ts
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/modules/block/ModuleBlockDetails.vue
  v2/src/modules/block/components/BlockDetails.vue
  v2/src/modules/block/components/BlockDetailsTitle.vue
  v2/src/modules/block/components/MoreBlockDetails.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTableRow.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/components/TxsTable.vue
  v2/src/modules/txs/components/TxsTableRow.vue
  v2/src/views/ViewBlockDetails.vue
Labels: ui, v2, refactor

#1056 Fix/address page update on hash change
  v2/src/core/components/AppAddressBlockie.vue
  v2/src/core/components/AppTabs.vue
  v2/src/core/composables/AddressEthBalance/addressEthBalance.composable.ts
  v2/src/core/composables/AddressTokens/addressTokens.composable.ts
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressPortfolio.vue
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/block/components/BlockStatsCard.vue
Labels: bug, v2

#1057 feat: tokens watchlist
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/core/components/AppBtn.vue
  v2/src/core/components/AppDialog.vue
  v2/src/core/components/AppInput.vue
  v2/src/core/components/AppTabs.vue
  v2/src/core/components/TheAppHeader.vue
  v2/src/core/composables/CoinData/coinData.composable.ts
  v2/src/core/plugins/vuetify.ts
  v2/src/modules/address/models/TokenSort.ts
  v2/src/modules/search/ModuleAppSearch.vue
  v2/src/modules/search/components/SearchCoreInput.vue
  v2/src/modules/tokens/ModuleAddFavToken.vue
  v2/src/modules/tokens/ModuleTokensInfo.vue
  v2/src/modules/tokens/components/TokenMarketInfo/TableRowTokenMarketInfo.vue
  v2/src/store/index.ts
  v2/src/views/ViewHome.vue
  v2/src/views/ViewTemp.vue
Labels: feature, ui, v2

#1060 fix: 🐛 token hash search not working
  v2/src/modules/search/ModuleAppSearch.vue
Labels: bug, v2

#1063 feat: 🎸 add search token to address balances
  v2/src/core/components/AppInput.vue
  v2/src/core/helper/search.ts
  v2/src/modules/address/ModuleAddressTokens.vue
Labels: v2
