Repository EthVM/EthVM, pull requests merged in 2022-08, with the labels that each got.

#1020 Feat/refactor address nft tokens
  v2/codegen.yml
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/index.ts
  v2/src/apollo/opensea/OpenSeaClient.ts
  v2/src/apollo/opensea/schema.graphql
  v2/src/apollo/types.ts
  v2/src/core/components/AppExpansionPanel.vue
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/modules/address/ModuleAdressNfts.vue
  v2/src/modules/address/apollo/tokens.generated.ts
  v2/src/modules/address/apollo/tokens.graphql
  v2/src/modules/address/components/AddressContractNfts.vue
  v2/src/views/AddressNftsView.vue
  v2/src/views/ViewTemp.vue
Labels: v2

#1022 feat: 🎸 complete tokens market info refactor
  v2/src/core/components/AppTableTitle.vue
  v2/src/core/composables/CoinData/coinData.composable.ts
  v2/src/core/router/index.ts
  v2/src/modules/tokens/ModuleTokensInfo.vue
  v2/src/views/TokensView.vue
Labels: v2

#1023 feat: address header
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/App.vue
  v2/src/core/components/AppError.vue
  v2/src/core/plugins/vuetify.ts
  v2/src/core/router/helpers.ts
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/modules/address/models/ErrorMessageAddress.ts
  v2/src/styles/settings.scss
  v2/src/views/AddressNftsView.vue
  v2/src/views/AddressTokensView.vue
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewTemp.vue
Labels: devop, ui, v2

#1025 Feat/pinia tokens balance
  v2/src/App.vue
  v2/src/core/components/AppSearch.vue
  v2/src/core/composables/AddressTokens/addressTokens.composable.ts
  v2/src/core/composables/AddressUpdate/addressUpdate.composable.ts
  v2/src/core/router/index.ts
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/ModuleAdressNfts.vue
  v2/src/modules/address/components/AddressContractNfts.vue
  v2/src/modules/address/models/TokenSort.ts
  v2/src/modules/block/ModuleBlockDetails.vue
  v2/src/modules/block/ModuleBlockStats.vue
  v2/src/modules/search/ModuleSearch.vue
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTableRow.vue
  v2/src/modules/tokens/components/TokenTransfers.vue
  v2/src/views/ViewAddressNfts.vue
  v2/src/views/ViewAddressOverview.vue
  v2/src/views/ViewAddressTokens.vue
  v2/src/views/ViewBlockDetails.vue
  v2/src/views/ViewBlocks.vue
  v2/src/views/ViewHome.vue
  v2/src/views/ViewTokenDetails.vue
  v2/src/views/ViewTokens.vue
  v2/src/views/ViewTxDetails.vue
  v2/src/views/ViewTxs.vue
  v2/src/views/ViewUncleDetails.vue
Labels: v2

#1027 Feat/eth balance UI
  v2/src/core/components/AppTokenIcon.vue
  v2/src/core/composables/AddressTokens/addressTokens.composable.ts
  v2/src/core/composables/CoinData/coinData.composable.ts
  v2/src/core/composables/CoinData/getLatestPrices.generated.ts
  v2/src/core/composables/CoinData/getLatestPrices.graphql
  v2/src/core/plugins/vuetify.ts
  v2/src/core/router/index.ts
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/modules/address/components/AddressBalanceTotals.vue
  v2/src/modules/address/components/AddressTokenFiatInfo.vue
  v2/src/styles/settings.scss
  v2/src/views/ViewAddressEthBalance.vue
  v2/src/views/ViewAddressOverview.vue
Labels: ui, v2

#1028 feat/refactor mining history
  v2/src/core/components/AppBtn.vue
  v2/src/core/components/AppIntersect.vue
  v2/src/core/components/AppNewUpdate.vue
  v2/src/core/components/AppPaginateHasMore.vue
  v2/src/core/composables/AddressTokens/addressTokens.composable.ts
  v2/src/core/composables/AddressUpdate/addressUpdate.composable.ts
  v2/src/core/helper/timeago.ts
  v2/src/core/plugins/vuetify.ts
  v2/src/core/router/helpers.ts
  v2/src/core/router/index.ts
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/ModuleAdressNfts.vue
  v2/src/modules/address/apollo/AddressBalance/addressBalance.generated.ts
  v2/src/modules/address/apollo/AddressBalance/addressBalance.graphql
  v2/src/modules/address/apollo/AddressEvent/addressEvent.generated.ts
  v2/src/modules/address/apollo/AddressEvent/addressEvent.graphql
  v2/src/modules/address/apollo/AddressRewards/rewards.generated.ts
  v2/src/modules/address/apollo/AddressRewards/rewards.graphql
  v2/src/modules/address/apollo/AddressTokens/tokens.generated.ts
  v2/src/modules/address/apollo/AddressTokens/tokens.graphql
  v2/src/modules/address/apollo/AddressTransfers/transfers.generated.ts
  v2/src/modules/address/apollo/AddressTransfers/transfers.graphql
  v2/src/modules/address/components/AddressContractNfts.vue
  v2/src/modules/address/models/TokenSort.ts
  v2/src/modules/tokens/apollo/TokenDetailsTransfer/tokenTransfers.generated.ts
  v2/src/styles/main.scss
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewAddressMiners.vue
  v2/src/views/ViewAddressOverview.vue
Labels: feature, ui, v2

#1029 Feat/adr potrfolio value
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/core/components/AppTokenIcon.vue
  v2/src/core/composables/AddressEthBalance/addressBalance.generated.ts
  v2/src/core/composables/AddressEthBalance/addressBalance.graphql
  v2/src/core/composables/AddressEthBalance/addressEthBalance.composable.ts
  v2/src/core/composables/AddressTokens/addressTokens.composable.ts
  v2/src/core/helper/number-format-helper.ts
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressPortfolio.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/components/AddressBalanceTotals.vue
  v2/src/modules/address/components/AddressTokenFiatInfo.vue
  v2/src/modules/chart/components/ChartPie.vue
  v2/src/styles/main.scss
  v2/src/views/ViewAddressEthBalance.vue
  v2/src/views/ViewAddressOverview.vue
Labels: feature, ui, v2

#1030 Feat/address top container
  v2/src/core/components/AppAddressBlockie.vue
  v2/src/core/components/AppMenu.vue
  v2/src/core/components/AppTransformHash.vue
  v2/src/core/helper/blockies.ts
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAddressPortfolio.vue
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewAddressOverview.vue
Labels: ui, v2
