Repository EthVM/EthVM, pull requests merged in 2023-06, with the labels that each got.

#1166 Feat/tx logs
  CHANGELOG.md
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/App.vue
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/assets/fonts/css/SourceCodePro.css
  v2/src/assets/fonts/fonts/source-code-pro-latin-regular.ttf
  v2/src/assets/fonts/fonts/source-code-pro-latin-regular.woff2
  v2/src/core/components/AppNoResult.vue
  v2/src/core/components/AppTabs.vue
  v2/src/core/helper/search.ts
  v2/src/core/plugins/vuetify.ts
  v2/src/core/router/routesNames.ts
  v2/src/main.ts
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/modules/txs/ModuleTxLogs.vue
  v2/src/modules/txs/apollo/TxDetails/TxDetails.generated.ts
  v2/src/modules/txs/apollo/TxDetails/TxDetails.graphql
  v2/src/modules/txs/components/TxLogRow.vue
  v2/src/store/index.ts
  v2/src/styles/settings.scss
  v2/src/translations/en_US.json
  v2/src/views/ViewAdWithUs.vue
  v2/src/views/ViewTxDetails.vue
Labels: feature

#1164 feat: translation for block-details
  CHANGELOG.md
  v2/src/modules/block/ModuleBlockWithdrawals.vue
  v2/src/modules/block/components/MoreBlockDetails.vue
  v2/src/translations/en_US.json
Labels: feature

#1161 Translation view address
  CHANGELOG.md
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressNfts.vue
  v2/src/modules/address/ModuleAddressRecentNfts.vue
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/ModuleAllEthTransfers.vue
  v2/src/modules/address/ModuleEthTxsHistory.vue
  v2/src/modules/address/ModuleInternalEthTransfers.vue
  v2/src/modules/address/ModulePendingEthTransfers.vue
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/ModuleStakeWithdrawals.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/components/TxsTable.vue
  v2/src/translations/en_US.json
Labels: feature

#1168 Translation view block
  CHANGELOG.md
  v2/src/modules/block/components/BlockDetails.vue
  v2/src/modules/block/components/MoreBlockDetails.vue
  v2/src/translations/en_US.json
Labels: feature

#1172 fix: to link in tx actions
  CHANGELOG.md
  v2/package.json
  v2/src/modules/txs/components/TxActionRow.vue
Labels: bug

#1162 Translation uncle details
  CHANGELOG.md
  v2/src/modules/uncles/ModuleUncleDetails.vue
  v2/src/translations/en_US.json
  v2/src/views/ViewUncleDetails.vue
Labels: ready, feature

#1170 Fix/sentry errors
  CHANGELOG.md
  v2/codegen.yml
  v2/src/App.vue
  v2/src/apollo/errorExceptions.ts
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/core/components/AppAdButtonsLarge.vue
  v2/src/main.ts
  v2/src/modules/block/ModuleRecentBlocks.vue
  v2/src/modules/tokens/components/TokenNFT/TokenNftDetails.vue
  v2/src/modules/tokens/components/TokenNFT/TokenNftImg.vue
  v2/src/modules/txs/ModuleTxActions.vue
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewHome.vue
Labels: bug, devop

#1171 Feat/add token routes
  CHANGELOG.md
  v2/package.json
  v2/src/core/router/helpers.ts
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/modules/tokens/ModuleTokensInfo.vue
  v2/src/views/ViewBlockDetails.vue
  v2/src/views/ViewPortfolio.vue
  v2/src/views/ViewTokenDetails.vue
  v2/src/views/ViewTokens.vue
  v2/src/views/ViewTxDetails.vue
Labels: bug, feature

#1173 Fix/eth balance
  CHANGELOG.md
  v2/src/core/composables/AddressEthBalance/addressEthBalance.composable.ts
  v2/src/core/composables/AddressTokens/addressTokens.composable.ts
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/ModulePortfolioList.vue
  v2/src/modules/address/ModulePortfolioTotal.vue
  v2/src/modules/address/components/AddressBalanceTotals.vue
  v2/src/modules/address/components/TableRowPortfolioItem.vue
  v2/src/views/ViewPortfolio.vue
Labels: bug

#1182 Release v2.1.4
  CHANGELOG.md
  v2/codegen.yml
  v2/package.json
  v2/src/App.vue
  v2/src/apollo/errorExceptions.ts
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/core/components/AppAdButtonsLarge.vue
  v2/src/core/composables/AddressEthBalance/addressEthBalance.composable.ts
  v2/src/core/composables/AddressTokens/addressTokens.composable.ts
  v2/src/core/router/helpers.ts
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/main.ts
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressNfts.vue
  v2/src/modules/address/ModuleAddressRecentNfts.vue
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/ModuleAllEthTransfers.vue
  v2/src/modules/address/ModuleEthTxsHistory.vue
  v2/src/modules/address/ModuleInternalEthTransfers.vue
  v2/src/modules/address/ModulePendingEthTransfers.vue
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/ModulePortfolioList.vue
  v2/src/modules/address/ModulePortfolioTotal.vue
  v2/src/modules/address/ModuleStakeWithdrawals.vue
  v2/src/modules/address/components/AddressBalanceTotals.vue
  v2/src/modules/address/components/TableRowPortfolioItem.vue
  v2/src/modules/block/ModuleBlockWithdrawals.vue
  v2/src/modules/block/ModuleRecentBlocks.vue
  v2/src/modules/block/components/BlockDetails.vue
  v2/src/modules/block/components/MoreBlockDetails.vue
  v2/src/modules/tokens/ModuleTokenDetails.vue
  v2/src/modules/tokens/ModuleTokensInfo.vue
  v2/src/modules/tokens/components/TokenDetails/TokenDetailsERC20.vue
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTable.vue
  v2/src/modules/tokens/components/TokenDetailsTransfer/TokenTransferTable.vue
  v2/src/modules/tokens/components/TokenNFT/TokenNftDetails.vue
  v2/src/modules/tokens/components/TokenNFT/TokenNftImg.vue
  v2/src/modules/txs/ModuleTxActions.vue
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/components/TxsTable.vue
  v2/src/modules/uncles/ModuleUncleDetails.vue
  v2/src/translations/en_US.json
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewBlockDetails.vue
  v2/src/views/ViewHome.vue
  v2/src/views/ViewPortfolio.vue
  v2/src/views/ViewTokenDetails.vue
  v2/src/views/ViewTokens.vue
  v2/src/views/ViewTxDetails.vue
  v2/src/views/ViewUncleDetails.vue
  v2/tsconfig.json
Labels: ready
