Repository EthVM/EthVM, pull requests merged in 2023-08, with the labels that each got.

#1189 Feat/vue meta
  CHANGELOG.md
  v2/package.json
  v2/pnpm-lock.yaml
  v2/public/index.html
  v2/public/logo2.png
  v2/public/ogImage.jpg
  v2/src/core/composables/use-page-meta/use-page-meta.composable.ts
  v2/src/core/helper/tags.ts
  v2/src/main.ts
  v2/src/views/ViewAbout.vue
  v2/src/views/ViewAdWithUs.vue
  v2/src/views/ViewAddressEthBalance.vue
  v2/src/views/ViewAddressNfts.vue
  v2/src/views/ViewAddressOverview.vue
  v2/src/views/ViewAddressTokens.vue
  v2/src/views/ViewBlockDetails.vue
  v2/src/views/ViewBlocks.vue
  v2/src/views/ViewHome.vue
  v2/src/views/ViewNotFound.vue
  v2/src/views/ViewPortfolio.vue
  v2/src/views/ViewPrivacyPolicy.vue
  v2/src/views/ViewSettings.vue
  v2/src/views/ViewTokenDetails.vue
  v2/src/views/ViewTokens.vue
  v2/src/views/ViewTxDetails.vue
  v2/src/views/ViewTxs.vue
  v2/src/views/ViewUncleDetails.vue
Labels: feature

#1201 feature: header ad banner for coinzilla
  CHANGELOG.md
  v2/package.json
  v2/public/index.html
  v2/src/core/components/TheAppHeader.vue
Labels: Ready For Review, feature

#1203 devop: update ad placement, make ui react to it
  CHANGELOG.md
  v2/package.json
  v2/src/core/components/TheAppHeader.vue
Labels: bug, ready
