Repository EthVM/EthVM, pull requests merged in 2023-03, with the labels that each got.

#1128 Devop/sentry
  .github/workflows/create-release.yml
  CHANGELOG.md
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/apollo/index.ts
  v2/src/configs.ts
  v2/src/main.ts
  v2/vue.config.js
Labels: devop

#1129 Devop/clean build
  CHANGELOG.md
  v2/public/index.html
  v2/src/apollo/opensea/OpenSeaClient.ts
  v2/src/core/components/AppInput.vue
  v2/src/core/components/AppMessage.vue
  v2/src/core/helper/search.ts
  v2/src/core/models/PendingTx.ts
  v2/src/core/models/index.ts
  v2/src/modules/address/ModulePortfolioList.vue
  v2/src/modules/address/models/TokenSort.ts
  v2/src/modules/block/ModuleBlockDetails.vue
  v2/src/modules/search/ModuleAppSearch.vue
  v2/src/views/ViewBlockDetails.vue
  v2/src/views/ViewTokenDetails.vue
  v2/src/views/ViewTxDetails.vue
  v2/src/views/ViewUncleDetails.vue
Labels: devop

#1133 Fix/empty search
  CHANGELOG.md
  v2/src/modules/search/ModuleAppSearch.vue
Labels: bug

#1134 Feat/search by domain
  CHANGELOG.md
  v2/codegen.yml
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/apollo/ens/ensClient.ts
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/index.ts
  v2/src/apollo/nfts/nftClient.ts
  v2/src/apollo/types.ts
  v2/src/core/components/AppInput.vue
  v2/src/core/composables/ResolveName/ensResolveName.generated.ts
  v2/src/core/composables/ResolveName/ensResolveName.graphql
  v2/src/core/composables/ResolveName/useResolveName.ts
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/search/ModuleAppSearch.vue
  v2/src/modules/search/components/SearchCoreInput.vue
  v2/src/typings/index.d.ts
  v2/tsconfig.json
Labels: feature

#1135 Devop/build improvements
  CHANGELOG.md
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/assets/fonts/css/Roboto.css
  v2/src/assets/fonts/fonts/roboto-v20-latin-300.eot
  v2/src/assets/fonts/fonts/roboto-v20-latin-300.svg
  v2/src/assets/fonts/fonts/roboto-v20-latin-300.ttf
  v2/src/assets/fonts/fonts/roboto-v20-latin-300.woff
  v2/src/assets/fonts/fonts/roboto-v20-latin-300.woff2
  v2/src/assets/fonts/fonts/roboto-v20-latin-500.eot
  v2/src/assets/fonts/fonts/roboto-v20-latin-500.svg
  v2/src/assets/fonts/fonts/roboto-v20-latin-500.ttf
  v2/src/assets/fonts/fonts/roboto-v20-latin-500.woff
  v2/src/assets/fonts/fonts/roboto-v20-latin-500.woff2
  v2/src/assets/fonts/fonts/roboto-v20-latin-700.eot
  v2/src/assets/fonts/fonts/roboto-v20-latin-700.svg
  v2/src/assets/fonts/fonts/roboto-v20-latin-700.ttf
  v2/src/assets/fonts/fonts/roboto-v20-latin-700.woff
  v2/src/assets/fonts/fonts/roboto-v20-latin-700.woff2
  v2/src/assets/fonts/fonts/roboto-v20-latin-regular.eot
  v2/src/assets/fonts/fonts/roboto-v20-latin-regular.svg
  v2/src/assets/fonts/fonts/roboto-v20-latin-regular.ttf
  v2/src/assets/fonts/fonts/roboto-v20-latin-regular.woff
  v2/src/assets/fonts/fonts/roboto-v20-latin-regular.woff2
  v2/src/core/plugins/vuetify.ts
  v2/src/core/plugins/webfontloader.ts
  v2/src/core/router/index.ts
  v2/src/main.ts
  v2/vue.config.js
Labels: devop

#1140 feat: created json for messages,update crowdin file
  CHANGELOG.md
  crowdin.yml
  v2/src/translations/en_US.json
  v2/src/translations/index.ts
  v2/tsconfig.json
Labels: feature

#1138 fix: catch invalid names
  CHANGELOG.md
  v2/package.json
  v2/src/core/composables/ResolveName/useResolveName.ts
  v2/src/main.ts
  v2/src/views/ViewAddress.vue
Labels: bug
