Repository EthVM/EthVM, pull requests merged in 2023-02, with the labels that each got.

#1098 feat: 🎸 add pagination to nft transfers and collections
  v2/src/core/components/AppPagination.vue
  v2/src/core/composables/AppPaginate/useAppPaginate.composable.ts
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressRecentNfts.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAllEthTransfers.vue
  v2/src/modules/address/ModuleEthTxsHistory.vue
  v2/src/modules/address/ModuleInternalEthTransfers.vue
  v2/src/modules/address/ModulePendingEthTransfers.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTable.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/components/TxsTable.vue
Labels: feature, v2

#1100 Feat/add pagination token markets page
  v2/src/modules/address/ModuleEthTxsHistory.vue
  v2/src/modules/tokens/ModuleTokensInfo.vue
Labels: feature, v2, refactor

#1101 Feat/add pagination portfolio balances
  v2/src/modules/address/ModulePortfolioTokenBalance.vue
Labels: feature, v2, refactor

#1099 Feat/nft contract collections
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/nfts/models.ts
  v2/src/apollo/nfts/nftClient.ts
  v2/src/apollo/nfts/schema.graphql
  v2/src/apollo/types.ts
  v2/src/core/composables/NftMeta/nftMeta.graphql
  v2/src/modules/tokens/ModuleTokenDetails.vue
  v2/src/modules/tokens/apollo/TokenDetails/tokenDetails.generated.ts
  v2/src/modules/tokens/apollo/TokenDetails/tokenDetails.graphql
  v2/src/modules/tokens/components/TokenDetails/TokenDetailsCollectionImg.vue
  v2/src/modules/tokens/components/TokenDetails/TokenDetailsERC20.vue
  v2/src/modules/tokens/components/TokenDetails/TokenDetailsNFT.vue
  v2/src/modules/tokens/components/TokenHolders.vue
  v2/src/styles/main.scss
  v2/src/styles/settings.scss
  v2/src/views/ViewTokenDetails.vue
Labels: feature, ui, v2

#1105 refactor: 💡 getEThTransfers query
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/apollo/transfersQuery.generated.ts
  v2/src/modules/txs/apollo/transfersQuery.graphql
Labels: v2, refactor

#1104 Feat/new tab UI
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/core/components/AppTableRow.vue
  v2/src/core/components/AppTabs.vue
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewAddressEthBalance.vue
Labels: ui, v2

#1106 Fix/nft meta in address
  v2/src/core/composables/AppPaginate/useAppPaginate.composable.ts
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressRecentNfts.vue
Labels: bug, v2

#1110 Feat/add pagination token transfers holders
  v2/src/core/composables/AppPaginate/useAppPaginate.composable.ts
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTable.vue
  v2/src/modules/tokens/components/TokenDetailsTransfer/TokenTransferTable.vue
  v2/src/modules/tokens/components/TokenHolders.vue
  v2/src/modules/tokens/components/TokenTransfers.vue
Labels: feature, v2

#1111 fix: 🐛 tab color on dark mode
  v2/src/views/ViewAddress.vue
Labels: bug, v2

#1108 fix: update home blocks table when new block comes in
  v2/src/modules/block/ModuleRecentBlocks.vue
Labels: bug, v2

#1112 Feat/logo route
  v2/src/assets/logo-dark.svg
  v2/src/core/components/TheAppFooter.vue
  v2/src/core/components/TheAppHeader.vue
  v2/src/core/components/TheAppNavigationDrawer.vue
  v2/src/core/router/helpers.ts
  v2/src/store/index.ts
Labels: feature, v2

#1113 Fix/pending tx not displaying
  v2/src/apollo/errorExceptions.ts
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/modules/txs/apollo/TxDetails.generated.ts
  v2/src/modules/txs/apollo/TxDetails.graphql
  v2/src/modules/txs/models/ErrorMessagesForTx.ts
  v2/src/views/ViewTxDetails.vue
Labels: bug, devop

#1114 Fix/UI small issues
  v2/public/favicon.ico
  v2/public/favicon.svg
  v2/public/index.html
  v2/src/core/components/AppTabs.vue
  v2/src/core/components/TheAppFooter.vue
  v2/src/core/components/TheAppNavigationDrawer.vue
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/ModulePortfolioList.vue
  v2/src/modules/address/ModulePortfolioTokenBalance.vue
  v2/src/modules/address/components/AddressTokenFiatInfo.vue
  v2/src/modules/address/components/TableRowTokenBalance.vue
  v2/src/modules/block/ModuleBlockDetails.vue
  v2/src/modules/block/apollo/BlockDetails/blockDetails.generated.ts
  v2/src/modules/block/apollo/BlockDetails/blockDetails.graphql
  v2/src/modules/block/components/BlockDetails.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTableRow.vue
  v2/src/modules/search/ModuleAppSearch.vue
  v2/src/modules/tokens/ModuleAddFavToken.vue
  v2/src/modules/tokens/ModuleTokensInfo.vue
  v2/src/modules/tokens/components/TokenDetails/TokenDetailsCollectionImg.vue
  v2/src/modules/tokens/components/TokenMarketInfo/TableRowTokenMarketInfo.vue
  v2/src/modules/txs/components/TableTabStateRow.vue
  v2/src/styles/settings.scss
  v2/src/views/ViewAddress.vue
Labels: bug, v2

#1115 Feat/token icons row
  v2/src/App.vue
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/core/components/AppInput.vue
  v2/src/core/components/AppTokenIcon.vue
  v2/src/core/components/AppTokenIconRow.vue
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressRecentNfts.vue
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/ModuleAllEthTransfers.vue
  v2/src/modules/address/ModuleEthTxsHistory.vue
  v2/src/modules/address/ModuleInternalEthTransfers.vue
  v2/src/modules/address/ModulePendingEthTransfers.vue
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/ModulePortfolioList.vue
  v2/src/modules/address/ModulePortfolioTokenBalance.vue
  v2/src/modules/address/ModulePortfolioTotal.vue
  v2/src/modules/address/apollo/AddressTokens/tokens.generated.ts
  v2/src/modules/address/apollo/AddressTokens/tokens.graphql
  v2/src/modules/address/components/AddressTokenFiatInfo.vue
  v2/src/modules/address/components/EthBalanceTabs/TableAllEthTransferRow.vue
  v2/src/modules/block/ModuleBlockDetails.vue
  v2/src/modules/block/components/MoreBlockDetails.vue
  v2/src/modules/search/components/SearchCoreInput.vue
  v2/src/modules/tokens/ModuleTokenDetails.vue
  v2/src/modules/tokens/ModuleTokensInfo.vue
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTable.vue
  v2/src/modules/tokens/components/TokenDetailsTransfer/TokenTransferTable.vue
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/components/TabMore.vue
  v2/src/modules/txs/components/TabState.vue
  v2/src/store/index.ts
  v2/src/views/ViewAddressEthBalance.vue
  v2/src/views/ViewAddressNfts.vue
  v2/src/views/ViewAddressOverview.vue
  v2/src/views/ViewAddressTokens.vue
  v2/src/views/ViewBlocks.vue
  v2/src/views/ViewBlocksAndTransactions.vue
  v2/src/views/ViewHome.vue
  v2/src/views/ViewNotFound.vue
  v2/src/views/ViewPortfolio.vue
  v2/src/views/ViewTokenDetails.vue
  v2/src/views/ViewTokens.vue
  v2/src/views/ViewTxDetails.vue
  v2/src/views/ViewTxs.vue
Labels: feature, v2

#1118 Fix/small bugs
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/App.vue
  v2/src/core/components/AppAddressBlockie.vue
  v2/src/core/components/TheAppFooter.vue
  v2/src/core/components/TheNotifications.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/components/AddressQr.vue
  v2/src/modules/address/components/TableRowAddressTokenTransfers.vue
  v2/src/modules/address/components/TableRowPortfolioItem.vue
  v2/src/modules/tokens/components/TokenDetails/TokenDetailsERC20.vue
  v2/src/modules/tokens/components/TokenDetailsList.vue
  v2/src/modules/tokens/components/TokenMarketInfo/TableRowTokenMarketInfo.vue
  v2/src/views/ViewAddress.vue
  v2/vue.config.js
Labels: bug, feature, v2

#1119 Feat/about us
  v2/src/App.vue
  v2/src/assets/logo/mew-long.svg
  v2/src/assets/promo/buy-crypto.png
  v2/src/assets/promo/enkrypt-purple-bg.svg
  v2/src/assets/promo/enkrypt-screen-sm.png
  v2/src/assets/promo/enkrypt-screen.png
  v2/src/assets/promo/enkrypt-text-sm.png
  v2/src/assets/promo/enkrypt-text.svg
  v2/src/assets/promo/mew.png
  v2/src/assets/promo/rarible.png
  v2/src/configs.ts
  v2/src/core/components/TheAppFooter.vue
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/components/AddressQr.vue
  v2/src/modules/block/ModuleRecentBlocks.vue
  v2/src/modules/tokens/ModuleTokensInfo.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/views/ViewAbout.vue
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewAddressMiners.vue
  v2/src/views/ViewHome.vue
  v2/src/views/ViewTemp.vue
Labels: feature, v2

#1123 Fix/develop release
  .github/workflows/add-to-develop.yml
  v2/checkBranch.sh
Labels: devop

#1126 Merge pull request #1125 from EthVM/develop
  .github/workflows/add-to-ethvmbuilds.yml
  .github/workflows/create-release.yml
  v2/package.json
Labels: devop
