Repository EthVM/EthVM, pull requests merged in 2023-01, with the labels that each got.

#1083 Fix/search portfolio
  v2/src/core/components/AppInput.vue
  v2/src/modules/address/ModulePortfolioTokenBalance.vue
Labels: bug, v2

#1084 feat: 🎸 add filter functionality to token markets page
  v2/src/modules/tokens/ModuleTokensInfo.vue
Labels: v2

#1079 Feat/create app table row
  v2/src/core/components/AppTableRow.vue
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/components/TableRowAddressTokenTransfers.vue
  v2/src/modules/address/components/TableRowMinerRewards.vue
  v2/src/modules/address/components/TableRowNftTransfers.vue
  v2/src/modules/address/components/TableRowTokenBalance.vue
  v2/src/modules/block/ModuleRecentBlocks.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTable.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTableRow.vue
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTable.vue
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTableRow.vue
  v2/src/modules/tokens/components/TokenDetailsTransfer/TokenTransferTable.vue
  v2/src/modules/tokens/components/TokenDetailsTransfer/TokenTransferTableRow.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/components/TxsTable.vue
  v2/src/modules/txs/components/TxsTableRow.vue
  v2/src/styles/main.scss
Labels: ui, v2, refactor

#1062 feat: portfolio
  v2/src/App.vue
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/core/components/AppAddressBlockie.vue
  v2/src/core/components/AppBtn.vue
  v2/src/core/components/AppCopyToClip.vue
  v2/src/core/components/AppInput.vue
  v2/src/core/components/AppTokenIcon.vue
  v2/src/core/components/AppTransformHash.vue
  v2/src/core/components/TheNotifications.vue
  v2/src/core/composables/AddressEthBalance/addressEthBalance.composable.ts
  v2/src/core/composables/AddressTokens/addressTokens.composable.ts
  v2/src/core/composables/AddressUpdate/addressUpdate.composable.ts
  v2/src/core/composables/AppNavigation/useAppNavigation.composable.ts
  v2/src/core/composables/Portfolio/useSetPortfolioBalance.ts
  v2/src/core/plugins/vuetify.ts
  v2/src/core/plugins/webfontloader.ts
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressPortfolio.vue
  v2/src/modules/address/ModuleAddressTokenBalance.vue
  v2/src/modules/address/ModuleAddressTokenTransfers.vue
  v2/src/modules/address/ModuleAddressTokens.vue
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/ModulePortfolioList.vue
  v2/src/modules/address/ModulePortfolioTokenBalance.vue
  v2/src/modules/address/ModulePortfolioTotal.vue
  v2/src/modules/address/components/AddressBalanceTotals.vue
  v2/src/modules/address/components/TableRowPortfolioItem.vue
  v2/src/modules/address/components/TableRowTokenBalance.vue
  v2/src/modules/chart/components/ChartPie.vue
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTableRow.vue
  v2/src/modules/tokens/components/TokenDetailsSocials.vue
  v2/src/modules/tokens/components/TokenMarketInfo/TableRowTokenMarketInfo.vue
  v2/src/store/helpers.ts
  v2/src/store/index.ts
  v2/src/styles/main.scss
  v2/src/styles/settings.scss
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewAddressOverview.vue
  v2/src/views/ViewPortfolio.vue
Labels: feature, devop, v2

#1065 Feat/address transfers history tables
  v2/src/App.vue
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/core/components/AppTableRow.vue
  v2/src/core/composables/AddressEthBalance/addressBalance.generated.ts
  v2/src/core/composables/AddressEthBalance/addressBalance.graphql
  v2/src/core/composables/IsAddressMiner/isAddressMiner.composable.ts
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/modules/address/ModuleAddressBalance.vue
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAllAndInternalEthTransfers.vue
  v2/src/modules/address/ModuleEthTxsHistory.vue
  v2/src/modules/address/ModulePendingEthTransfers.vue
  v2/src/modules/address/apollo/AddressTransfers/transfers.graphql
  v2/src/modules/address/apollo/EthTransfers/allTransfers.generated.ts
  v2/src/modules/address/apollo/EthTransfers/allTransfers.graphql
  v2/src/modules/address/apollo/EthTransfers/internalTransfers.generated.ts
  v2/src/modules/address/apollo/EthTransfers/internalTransfers.graphql
  v2/src/modules/address/apollo/EthTransfers/pendingTransfers.generated.ts
  v2/src/modules/address/apollo/EthTransfers/pendingTransfers.graphql
  v2/src/modules/address/apollo/EthTransfers/transfersHistory.generated.ts
  v2/src/modules/address/apollo/EthTransfers/transfersHistory.graphql
  v2/src/modules/address/components/EthBalanceTabs/TableAllAndInternalRow.vue
  v2/src/modules/address/components/EthBalanceTabs/TablePendingRow.vue
  v2/src/modules/address/components/EthBalanceTabs/TableTxsHistoryRow.vue
  v2/src/modules/address/components/TableRowPortfolioItem.vue
  v2/src/modules/txs/components/TableTabStateRow.vue
  v2/src/styles/main.scss
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewAddressEthBalance.vue
  v2/src/views/ViewAddressOverview.vue
Labels: ui, v2, refactor

#1085 feat: 🎸 add pagination to tx table
  v2/src/core/composables/AppPaginate/useAppPaginate.composable.ts
  v2/src/modules/block/ModuleRecentBlocks.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTable.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/components/TxsTable.vue
Labels: v2, refactor

#1089 Devop/nft trasfers api update
  v2/src/core/composables/NftMeta/helpers.ts
  v2/src/core/composables/NftMeta/model.ts
  v2/src/core/composables/NftMeta/useGetNftsMeta.composable.ts
  v2/src/core/helper/timeago.ts
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressRecentNfts.vue
  v2/src/modules/address/apollo/AddressTransfers/transfers.generated.ts
  v2/src/modules/address/apollo/AddressTransfers/transfers.graphql
  v2/src/modules/address/components/TableRowNftTransfers.vue
  v2/src/modules/tokens/apollo/TokenDetailsTransfer/tokenTransfers.generated.ts
  v2/src/modules/tokens/apollo/TokenDetailsTransfer/tokenTransfers.graphql
  v2/src/modules/tokens/components/TokenNFT/TokenNftImg.vue
  v2/src/styles/settings.scss
Labels: feature, devop, v2

#1090 Devop/nft adr balance api update
  v2/src/modules/address/ModuleAddressNfts.vue
  v2/src/modules/address/ModuleAddressRecentNfts.vue
  v2/src/modules/address/apollo/AddressTokens/tokens.generated.ts
  v2/src/modules/address/apollo/AddressTokens/tokens.graphql
  v2/src/modules/address/components/AddressContractNfts.vue
  v2/src/modules/tokens/components/TokenNFT/TokenNftDetails.vue
  v2/src/modules/tokens/components/TokenNFT/TokenNftImg.vue
  v2/src/modules/tokens/components/TokenNFT/propModel.ts
  v2/src/views/ViewAddressNfts.vue
  v2/src/views/ViewAddressOverview.vue
Labels: feature, ui, v2

#1086 Feat/recent owned nft
  v2/codegen.yml
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/index.ts
  v2/src/apollo/nfts/models.ts
  v2/src/apollo/nfts/nftClient.ts
  v2/src/apollo/nfts/schema.graphql
  v2/src/apollo/types.ts
  v2/src/assets/icon-nft.png
  v2/src/core/components/AppDialog.vue
  v2/src/core/composables/NftMeta/helpers.ts
  v2/src/core/composables/NftMeta/nftMeta.generated.ts
  v2/src/core/composables/NftMeta/nftMeta.graphql
  v2/src/core/composables/NftMeta/useGetNftsMeta.composable.ts
  v2/src/core/helper/timeago.ts
  v2/src/modules/address/ModuleAddressNftTransfers.vue
  v2/src/modules/address/ModuleAddressNfts.vue
  v2/src/modules/address/ModuleAddressRecentNfts.vue
  v2/src/modules/address/apollo/AddressTokens/tokens.generated.ts
  v2/src/modules/address/apollo/AddressTokens/tokens.graphql
  v2/src/modules/address/apollo/AddressTransfers/transfers.generated.ts
  v2/src/modules/address/apollo/AddressTransfers/transfers.graphql
  v2/src/modules/address/components/AddressContractNfts.vue
  v2/src/modules/address/components/TableRowNftTransfers.vue
  v2/src/modules/tokens/apollo/TokenDetailsTransfer/tokenTransfers.generated.ts
  v2/src/modules/tokens/apollo/TokenDetailsTransfer/tokenTransfers.graphql
  v2/src/modules/tokens/components/TokenNFT/TokenNftDetails.vue
  v2/src/modules/tokens/components/TokenNFT/TokenNftImg.vue
  v2/src/modules/tokens/components/TokenNFT/propModel.ts
  v2/src/styles/main.scss
  v2/src/styles/settings.scss
  v2/src/views/ViewAddressNfts.vue
  v2/src/views/ViewAddressOverview.vue
Labels: feature, v2

#1092 Feat/nft contract api update
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/modules/tokens/apollo/TokenDetailsTransfer/tokenTransfers.generated.ts
  v2/src/modules/tokens/apollo/TokenDetailsTransfer/tokenTransfers.graphql
  v2/src/modules/tokens/components/TokenDetailsTransfer/TokenTransferTable.vue
  v2/src/modules/tokens/components/TokenDetailsTransfer/TokenTransferTableRow.vue
  v2/src/modules/tokens/components/TokenTransfers.vue
Labels: feature, v2

#1095 feat: erc1155 token owners to contract, new nft owner layout
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/modules/tokens/apollo/TokenDetails/tokenDetails.generated.ts
  v2/src/modules/tokens/apollo/TokenDetails/tokenDetails.graphql
  v2/src/modules/tokens/apollo/TokenDetailsHolder/tokenHolders.generated.ts
  v2/src/modules/tokens/apollo/TokenDetailsHolder/tokenHolders.graphql
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTable.vue
  v2/src/modules/tokens/components/TokenDetailsHolder/TokenHolderTableRow.vue
  v2/src/modules/tokens/components/TokenHolders.vue
  v2/src/modules/tokens/components/TokenNFT/propModel.ts
Labels: feature, ui, v2

#1082 Feat/app pagination
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/core/components/AppPaginate.vue
  v2/src/core/components/AppPaginateHasMore.vue
  v2/src/core/components/AppPagination.vue
  v2/src/core/composables/AppPaginate/useAppPaginate.composable.ts
  v2/src/core/constants.ts
  v2/src/modules/address/ModuleAddressMinerBlock.vue
  v2/src/modules/address/ModuleAllAndInternalEthTransfers.vue
  v2/src/modules/address/ModuleAllEthTransfers.vue
  v2/src/modules/address/ModuleEthTxsHistory.vue
  v2/src/modules/address/ModuleInternalEthTransfers.vue
  v2/src/modules/address/ModulePendingEthTransfers.vue
  v2/src/modules/address/apollo/EthTransfers/internalTransfers.generated.ts
  v2/src/modules/address/apollo/EthTransfers/internalTransfers.graphql
  v2/src/modules/address/components/EthBalanceTabs/TableAllEthTransferRow.vue
  v2/src/modules/address/components/EthBalanceTabs/TableInternalEthTransferRow.vue
  v2/src/modules/address/components/EthBalanceTabs/TablePendingRow.vue
  v2/src/modules/address/components/EthBalanceTabs/TableTxsHistoryRow.vue
  v2/src/modules/block/ModuleRecentBlocks.vue
  v2/src/modules/block/apollo/RecentBlocks/recentBlocks.generated.ts
  v2/src/modules/block/apollo/RecentBlocks/recentBlocks.graphql
  v2/src/modules/block/components/RecentBlocks/BlocksTable.vue
  v2/src/modules/block/components/RecentBlocks/NoticeNewBlock.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/components/TxsTable.vue
  v2/src/store/index.ts
  v2/src/views/ViewAddressEthBalance.vue
  v2/src/views/ViewAddressOverview.vue
Labels: v2, refactor

#1096 Feat/add pagination pending txs
  v2/src/modules/address/ModulePendingEthTransfers.vue
  v2/src/modules/address/apollo/EthTransfers/pendingTransfers.generated.ts
  v2/src/modules/address/apollo/EthTransfers/pendingTransfers.graphql
Labels: feature, v2
