Repository EthVM/EthVM, pull requests merged in 2023-05, with the labels that each got.

#1151 devop: prevent fetching isMiner if hash is not valid
  CHANGELOG.md
  v2/src/core/composables/IsAddressMiner/isAddressMiner.composable.ts
  v2/src/views/ViewAddress.vue
Labels: devop

#1152 Feat/search improvemetns
  CHANGELOG.md
  v2/src/modules/search/ModuleAppSearch.vue
  v2/src/modules/search/components/SearchCoreInput.vue
  v2/src/modules/txs/ModuleTxs.vue
Labels: feature

#1153 Feat/tx actions
  CHANGELOG.md
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/core/components/AppExpansionPanel.vue
  v2/src/core/components/AppTooltip.vue
  v2/src/core/components/AppTransformHash.vue
  v2/src/core/components/TheNotifications.vue
  v2/src/core/composables/Network/useNetwork.ts
  v2/src/core/helper/networks.ts
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/modules/search/ModuleAppSearch.vue
  v2/src/modules/txs/ModuleTxActions.vue
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/modules/txs/apollo/Actions/actionsQueries.generated.ts
  v2/src/modules/txs/apollo/Actions/actionsQueries.graphql
  v2/src/modules/txs/apollo/TxDetails/TxDetails.generated.ts
  v2/src/modules/txs/apollo/TxDetails/TxDetails.graphql
  v2/src/modules/txs/components/TabMore.vue
  v2/src/modules/txs/components/TxActionRow.vue
  v2/src/modules/txs/types/index.ts
Labels: feature, devop

#1157 Release v2.1.1
  CHANGELOG.md
  v2/package.json
  v2/pnpm-lock.yaml
  v2/src/apollo/errorExceptions.ts
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/core/components/AppExpansionPanel.vue
  v2/src/core/components/AppTooltip.vue
  v2/src/core/components/AppTransformHash.vue
  v2/src/core/components/TheNotifications.vue
  v2/src/core/composables/IsAddressMiner/isAddressMiner.composable.ts
  v2/src/core/composables/Network/useNetwork.ts
  v2/src/core/composables/ResolveName/useResolveName.ts
  v2/src/core/helper/networks.ts
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/main.ts
  v2/src/modules/block/ModuleBlockDetails.vue
  v2/src/modules/block/ModuleBlockWithdrawals.vue
  v2/src/modules/block/apollo/BlockDetails/blockDetails.generated.ts
  v2/src/modules/block/apollo/BlockDetails/blockDetails.graphql
  v2/src/modules/search/ModuleAppSearch.vue
  v2/src/modules/search/components/SearchCoreInput.vue
  v2/src/modules/txs/ModuleTxActions.vue
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/modules/txs/ModuleTxs.vue
  v2/src/modules/txs/apollo/Actions/actionsQueries.generated.ts
  v2/src/modules/txs/apollo/Actions/actionsQueries.graphql
  v2/src/modules/txs/apollo/TxDetails/TxDetails.generated.ts
  v2/src/modules/txs/apollo/TxDetails/TxDetails.graphql
  v2/src/modules/txs/components/TabMore.vue
  v2/src/modules/txs/components/TxActionRow.vue
  v2/src/modules/txs/types/index.ts
  v2/src/views/ViewAddress.vue
Labels: ready

#1142 feat: translate homepage(top,fav token, tagline, footer)
  CHANGELOG.md
  v2/src/core/components/TheAppFooter.vue
  v2/src/modules/block/ModuleRecentBlocks.vue
  v2/src/modules/block/components/RecentBlocks/BlocksTable.vue
  v2/src/modules/tokens/ModuleTokensInfo.vue
  v2/src/translations/en_US.json
  v2/src/views/ViewHome.vue
Labels: feature

#1155 Translation portfolio
  CHANGELOG.md
  v2/src/modules/address/ModulePorfolioHandleAdr.vue
  v2/src/modules/address/ModulePortfolioList.vue
  v2/src/modules/address/ModulePortfolioTokenBalance.vue
  v2/src/modules/address/ModulePortfolioTotal.vue
  v2/src/translations/en_US.json
  v2/src/views/ViewPortfolio.vue
Labels: feature

#1158 Feat:Translation settings
  CHANGELOG.md
  v2/src/modules/settings/ModuleAddressNames.vue
  v2/src/modules/settings/ModuleSettings.vue
  v2/src/translations/en_US.json
Labels: feature

#1159 feat: translation for txs detailed
  CHANGELOG.md
  v2/src/modules/txs/ModuleTxActions.vue
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/modules/txs/components/TabMore.vue
  v2/src/modules/txs/components/TabState.vue
  v2/src/modules/txs/components/TxActionRow.vue
  v2/src/modules/txs/components/TxsTable.vue
  v2/src/translations/en_US.json
Labels: feature

#1156 Feat/advertise
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-ethvmbuilds.yml
  .github/workflows/add-to-sepolia.yml
  .github/workflows/add-to-staging.yml
  .github/workflows/create-release.yml
  CHANGELOG.md
  v2/pnpm-lock.yaml
  v2/src/App.vue
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/assets/hero/hero-messanger.png
  v2/src/assets/promo/ad-guide.png
  v2/src/assets/promo/mew-universe.png
  v2/src/configs.ts
  v2/src/core/components/TheAppFooter.vue
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/styles/defaults.scss
  v2/src/translations/en_US.json
  v2/src/views/ViewAdWithUs.vue
  v2/src/views/ViewHome.vue
Labels: feature

#1163 hotfix-transfers
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-ethvmbuilds.yml
  .github/workflows/add-to-sepolia.yml
  .github/workflows/add-to-staging.yml
  .github/workflows/create-release.yml
  CHANGELOG.md
  v2/package.json
  v2/src/apollo/graphql.schema.json
  v2/src/apollo/types.ts
  v2/src/modules/address/apollo/AddressTransfers/transfers.generated.ts
  v2/src/modules/address/apollo/AddressTransfers/transfers.graphql
  v2/src/modules/txs/ModuleTxLogs.vue
Labels: devop

#1160 Feat/internal promo
  .github/workflows/add-to-develop.yml
  .github/workflows/add-to-ethvmbuilds.yml
  .github/workflows/add-to-sepolia.yml
  .github/workflows/add-to-staging.yml
  .github/workflows/create-release.yml
  CHANGELOG.md
  v2/package.json
  v2/pnpm-lock.yaml
  v2/public/index.html
  v2/public/logo2.png
  v2/src/App.vue
  v2/src/assets/logo/mew-long-white.png
  v2/src/assets/promo/banner-sm-enkrypt.png
  v2/src/assets/promo/banner-sm-mewtopia.png
  v2/src/assets/promo/banner-sm-mewwallet.png
  v2/src/assets/promo/banner-sm-raffle.png
  v2/src/assets/promo/btn-enkrypt.png
  v2/src/assets/promo/btn-mew.png
  v2/src/assets/promo/btn-mewwallet.png
  v2/src/assets/promo/btn-raffle.png
  v2/src/assets/promo/btn-twitter.png
  v2/src/assets/promo/rarible-icon.png
  v2/src/configs.ts
  v2/src/core/components/AppAdButtonsLarge.vue
  v2/src/core/components/AppAdButtonsSmall.vue
  v2/src/core/components/TheAppFooter.vue
  v2/src/core/composables/AppNavigation/useAppNavigation.composable.ts
  v2/src/core/router/index.ts
  v2/src/core/router/routesNames.ts
  v2/src/main.ts
  v2/src/modules/block/ModuleBlockDetails.vue
  v2/src/modules/block/components/BlockDetails.vue
  v2/src/modules/settings/ModuleSettings.vue
  v2/src/modules/tokens/ModuleTokenDetails.vue
  v2/src/modules/txs/ModuleTxDetails.vue
  v2/src/store/helpers.ts
  v2/src/store/index.ts
  v2/src/translations/en_US.json
  v2/src/views/ViewAbout.vue
  v2/src/views/ViewAddress.vue
  v2/src/views/ViewAddressEthBalance.vue
  v2/src/views/ViewAddressNfts.vue
  v2/src/views/ViewAddressOverview.vue
  v2/src/views/ViewAddressTokens.vue
  v2/src/views/ViewBlockDetails.vue
  v2/src/views/ViewBlocks.vue
  v2/src/views/ViewHome.vue
  v2/src/views/ViewPortfolio.vue
  v2/src/views/ViewPrivacyPolicy.vue
  v2/src/views/ViewSettings.vue
  v2/src/views/ViewTokens.vue
  v2/src/views/ViewTxs.vue
  v2/src/views/ViewUncleDetails.vue
Labels: feature
